version: '3'
services:
  db:
    container_name: db
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306

    volumes:
      - ./data:/var/lib/mysql/

#  backend:
#    container_name: backend
#    build: ./facebox-backend
#    ports:
#      - "8081:8081"
#    depends_on:
#      - db

  frontend:
    build: ./facebox-frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
